project_id = "ufzxrojekrrvlweadnkq"

[functions.admin-list-users]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-add-org-member]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false
