version: '3.8'

services:
  resume-builder:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # Optional: Mount nginx config if you want to customize it
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - resume-app

networks:
  resume-app:
    driver: bridge

# Optional: Add volume for persistent data if needed
# volumes:
#   app-data: