// Template styles for Tailwind-based rendering (used by TemplateGallery/Examples pages)
// These map to the same 7 premium templates defined in resumeTemplates.tsx

export const templateStyles: Record<string, Record<string, string>> = {
  'clean-slate': {
    container: "font-sans max-w-4xl mx-auto bg-white shadow-lg border-t-[3px] border-blue-600",
    header: "p-8 border-b border-gray-200",
    headerName: "text-3xl font-bold text-gray-900 tracking-tight",
    headerTitle: "text-lg mt-2 text-gray-600",
    headerContact: "mt-4 flex flex-wrap gap-4 text-sm text-gray-500",
    section: "px-8 py-4 border-b border-gray-100",
    sectionTitle: "text-xs font-bold uppercase tracking-[0.2em] text-blue-600 mb-3 pb-1.5 border-b-[1.5px] border-blue-100",
    subsection: "mb-4",
    subsectionTitle: "text-base font-semibold flex justify-between text-gray-900",
    subsectionDate: "text-gray-400 text-sm",
    subsectionContent: "mt-2 text-gray-600 leading-relaxed text-sm",
    skillsContainer: "flex flex-wrap gap-2",
    skillBadge: "bg-blue-50 text-blue-700 px-3 py-1 rounded text-xs border border-blue-200",
  },

  'executive-serif': {
    container: "font-serif max-w-4xl mx-auto bg-white shadow-xl",
    header: "text-center py-10 border-b-[3px] border-double border-gray-900",
    headerName: "text-4xl font-bold text-gray-900 tracking-wide uppercase",
    headerTitle: "text-xl mt-3 text-gray-600 italic",
    headerContact: "mt-5 flex justify-center flex-wrap gap-6 text-base text-gray-500",
    section: "px-10 py-5 border-b border-gray-200",
    sectionTitle: "text-sm font-bold uppercase tracking-[0.25em] text-gray-900 mb-4 pb-2 border-b-2 border-gray-900 text-center",
    subsection: "mb-6",
    subsectionTitle: "text-lg font-bold text-gray-900 flex justify-between",
    subsectionDate: "text-gray-500 italic",
    subsectionContent: "mt-3 text-gray-700 leading-loose text-base",
    skillsContainer: "flex flex-wrap gap-3 justify-center",
    skillBadge: "border-[1.5px] border-gray-700 text-gray-800 px-4 py-1.5 text-sm",
  },

  'sidebar-modern': {
    container: "font-sans max-w-4xl mx-auto bg-white shadow-xl border-l-[6px] border-violet-600",
    header: "p-8 border-b border-gray-200 flex items-center gap-5",
    headerName: "text-3xl font-bold text-violet-600 tracking-tight",
    headerTitle: "text-lg mt-2 text-gray-600",
    headerContact: "mt-4 flex flex-wrap gap-4 text-sm text-gray-500",
    section: "px-8 py-4",
    sectionTitle: "text-xs font-bold uppercase tracking-[0.15em] text-violet-600 mb-3 pb-1.5 border-b-2 border-violet-100",
    subsection: "mb-4 pl-3.5 border-l-2 border-violet-100",
    subsectionTitle: "text-base font-semibold flex justify-between text-gray-900",
    subsectionDate: "text-violet-500 text-sm",
    subsectionContent: "mt-2 text-gray-600 leading-relaxed text-sm",
    skillsContainer: "flex flex-wrap gap-2",
    skillBadge: "bg-violet-50 text-violet-700 px-3.5 py-1 rounded-full text-xs border border-violet-200",
  },

  'tech-engineer': {
    container: "font-mono max-w-4xl mx-auto bg-white shadow-2xl",
    header: "bg-slate-900 text-cyan-300 p-8 flex items-center gap-5",
    headerName: "text-3xl font-bold tracking-wider text-cyan-300",
    headerTitle: "text-lg mt-2 opacity-80",
    headerContact: "mt-4 flex flex-wrap gap-4 text-sm text-slate-400",
    section: "px-8 py-4 border-b border-gray-100",
    sectionTitle: "text-xs font-bold uppercase tracking-[0.15em] text-slate-900 mb-3 mt-4 pb-1 border-b-2 border-slate-900",
    subsection: "mb-4",
    subsectionTitle: "text-sm font-semibold flex justify-between text-gray-900",
    subsectionDate: "text-gray-500 text-xs font-mono",
    subsectionContent: "mt-2 text-gray-600 leading-relaxed text-sm font-mono",
    skillsContainer: "flex flex-wrap gap-1.5",
    skillBadge: "bg-slate-900 text-cyan-300 px-2.5 py-1 rounded text-xs font-mono border border-slate-700",
  },

  'coral-creative': {
    container: "font-sans max-w-4xl mx-auto bg-white shadow-xl",
    header: "p-8 border-b border-rose-100 flex items-center gap-5",
    headerName: "text-3xl font-bold text-rose-600 tracking-tight",
    headerTitle: "text-lg mt-2 text-gray-600",
    headerContact: "mt-4 flex flex-wrap gap-4 text-sm text-gray-500",
    section: "px-8 py-4",
    sectionTitle: "text-xs font-bold uppercase tracking-[0.15em] text-rose-600 mb-3 pb-1.5 border-b-2 border-rose-200",
    subsection: "mb-4 pl-3.5 border-l-[3px] border-rose-200",
    subsectionTitle: "text-base font-semibold flex justify-between text-gray-900",
    subsectionDate: "text-rose-500 text-sm",
    subsectionContent: "mt-2 text-gray-600 leading-relaxed text-sm",
    skillsContainer: "flex flex-wrap gap-2",
    skillBadge: "bg-rose-50 text-rose-700 px-3.5 py-1 rounded-full text-xs border border-rose-200",
  },

  'navy-professional': {
    container: "font-sans max-w-4xl mx-auto bg-white shadow-xl border-t-[5px] border-[#1e3a5f]",
    header: "p-8 border-b border-gray-200",
    headerName: "text-3xl font-bold text-[#1e3a5f] tracking-tight",
    headerTitle: "text-lg mt-2 text-gray-600",
    headerContact: "mt-4 flex flex-wrap gap-4 text-sm text-gray-500",
    section: "px-8 py-4 border-b border-gray-100",
    sectionTitle: "text-xs font-bold uppercase tracking-[0.15em] text-[#1e3a5f] mb-3 pb-1.5 border-b-[2.5px] border-[#1e3a5f]",
    subsection: "mb-5",
    subsectionTitle: "text-base font-semibold flex justify-between text-gray-900",
    subsectionDate: "text-[#1e3a5f] text-sm font-medium",
    subsectionContent: "mt-2 text-gray-700 leading-relaxed",
    skillsContainer: "flex flex-wrap gap-2",
    skillBadge: "bg-[#1e3a5f] text-white px-3.5 py-1.5 rounded text-xs font-medium",
  },

  'emerald-minimal': {
    container: "font-sans max-w-4xl mx-auto bg-white shadow-lg border-l-4 border-emerald-600",
    header: "p-8 border-b border-emerald-100",
    headerName: "text-3xl font-semibold text-emerald-900 tracking-tight",
    headerTitle: "text-lg mt-2 text-gray-600",
    headerContact: "mt-4 flex flex-wrap gap-4 text-sm text-gray-500",
    section: "px-8 py-4",
    sectionTitle: "text-[11px] font-bold uppercase tracking-[0.2em] text-emerald-600 mb-3 pb-1 border-b-[1.5px] border-emerald-200",
    subsection: "mb-4",
    subsectionTitle: "text-base font-semibold flex justify-between text-gray-900",
    subsectionDate: "text-emerald-600 text-sm",
    subsectionContent: "mt-2 text-gray-600 leading-relaxed text-sm",
    skillsContainer: "flex flex-wrap gap-2",
    skillBadge: "bg-emerald-50 text-emerald-800 px-3 py-1 rounded text-xs border border-emerald-200",
  },
};
