export const SITE_NAME = 'MakeCV';
export const DEFAULT_SITE_URL = 'https://makecv.site';
export const DEFAULT_OG_IMAGE = '/og-image.png';

export function getSiteUrl() {
  return (process.env.VITE_SITE_URL || DEFAULT_SITE_URL).replace(/\/+$/, '');
}

// Public, canonical routes intentionally indexed by search engines.
export const PUBLIC_ROUTES = [
  {
    path: '/',
    title: 'Make CV Online Free — Make Your Resume & ATS CV Builder',
    description: 'Make your resume online for free with MakeCV. Make a CV or resume in minutes with 30+ ATS-friendly templates, AI writing assistance, and instant PDF download. No credit card required.',
    heading: 'Make CV & Resume Online Free with AI Assistance',
    changefreq: 'weekly',
    priority: '1.0',
    type: 'WebApplication',
  },
  {
    path: '/make-cv',
    title: 'Make CV Online Free — Fast & Professional CV Maker',
    description: 'Make your CV online for free with MakeCV. Choose from 30+ ATS-friendly templates, customize with AI bullet point suggestions, and download your polished PDF instantly.',
    heading: 'Make Your CV Online Free in Minutes',
    changefreq: 'weekly',
    priority: '0.95',
    type: 'WebApplication',
  },
  {
    path: '/make-resume',
    title: 'Make Resume Online Free — ATS Resume Builder',
    description: 'Make your resume online for free with MakeCV. Build an ATS-optimized resume tailored to any job description with AI suggestions and instant PDF export.',
    heading: 'Make Your Resume Online for Free',
    changefreq: 'weekly',
    priority: '0.95',
    type: 'WebApplication',
  },
  {
    path: '/cv-maker',
    title: 'Online CV Maker — Create Professional CVs for Free',
    description: 'The #1 free online CV maker. Create a standout curriculum vitae with ATS-friendly layouts, AI writing tools, and high-resolution PDF download.',
    heading: 'The Free Online CV Maker Built for Results',
    changefreq: 'weekly',
    priority: '0.95',
    type: 'WebApplication',
  },
  {
    path: '/resume-builder',
    title: 'Make Resume Online Free — ATS-Friendly AI Resume Builder',
    description: 'Create a professional, ATS-friendly resume online for free. Choose a template, add your experience, and download a polished PDF in minutes.',
    heading: 'Free Online Resume Builder',
    changefreq: 'weekly',
    priority: '0.9',
    type: 'WebApplication',
  },
  {
    path: '/templates',
    title: '30+ Free ATS Resume & CV Templates — Make Your CV Online',
    description: 'Browse 30+ free, ATS-optimized resume templates for every industry. Customize any design and download your professional resume as a PDF.',
    heading: 'Free Resume Templates',
    changefreq: 'weekly',
    priority: '0.9',
  },
  {
    path: '/cover-letter-builder',
    title: 'Free AI Cover Letter Builder — Make Matching Cover Letters',
    description: 'Write a tailored, professional cover letter with AI assistance. Match it to your resume, edit every detail, and download it as a PDF.',
    heading: 'Free Cover Letter Builder',
    changefreq: 'monthly',
    priority: '0.8',
    type: 'WebApplication',
  },
  {
    path: '/pricing',
    title: 'Resume Builder Pricing — Free and Premium Plans',
    description: 'Start with MakeCV for free. Compare resume builder plans with AI suggestions, unlimited resumes, version history, and cloud backup.',
    heading: 'Simple Resume Builder Pricing',
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/features',
    title: 'Make CV Features — AI Bullet Suggestions, ATS Scoring & Templates',
    description: 'Explore MakeCV features including ATS-friendly templates, live preview, AI writing help, PDF export, cloud storage, and resume sharing.',
    heading: 'Everything You Need to Build a Better Resume',
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/examples',
    title: 'Professional Resume & CV Examples by Industry',
    description: 'Browse professional resume examples across industries and experience levels. Use an example as inspiration and build your own resume online.',
    heading: 'Professional Resume Examples',
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/blog',
    title: 'Resume Tips and Career Advice Blog',
    description: 'Read practical resume writing tips, career advice, ATS guidance, and job search strategies from the MakeCV team.',
    heading: 'Resume Tips and Career Advice',
    changefreq: 'daily',
    priority: '0.8',
  },
  {
    path: '/resources',
    title: 'Free Resume Resources and Job Search Tools',
    description: 'Find free resume templates, examples, career advice, and job search resources to build a stronger application and land more interviews.',
    heading: 'Free Resume Resources',
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/career-advice',
    title: 'Career Advice and Job Search Tips',
    description: 'Get practical career advice for writing resumes, preparing for interviews, negotiating offers, and advancing your career.',
    heading: 'Career Advice and Job Search Tips',
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/login',
    title: 'Log In to MakeCV',
    description: 'Log in to MakeCV to build resumes, create cover letters, manage your templates, and continue your job search workspace.',
    heading: 'Log In to MakeCV',
    changefreq: 'yearly',
    priority: '0.4',
  },
  {
    path: '/help',
    title: 'MakeCV Help Center and Support',
    description: 'Find answers about MakeCV resume tools, accounts, downloads, billing, and support.',
    heading: 'MakeCV Help Center',
    changefreq: 'monthly',
    priority: '0.5',
  },
  {
    path: '/about',
    title: 'About MakeCV',
    description: 'Learn about MakeCV, founded by Nishant Jha, the online resume and cover letter builder designed to help job seekers create professional applications.',
    heading: 'About MakeCV',
    changefreq: 'yearly',
    priority: '0.5',
  },
  {
    path: '/ats',
    title: 'Applicant Tracking System for Collaborative Hiring',
    description: 'Manage jobs, candidates, hiring pipelines, team feedback, and recruiting analytics with MakeCV ATS.',
    heading: 'Hire Smarter, Faster, Together',
    changefreq: 'monthly',
    priority: '0.6',
    type: 'SoftwareApplication',
  },
  {
    path: '/ats/jobs/browse',
    title: 'Browse Open Jobs',
    description: 'Browse current job openings published by hiring teams using MakeCV ATS.',
    heading: 'Browse Open Jobs',
    changefreq: 'daily',
    priority: '0.6',
  },
  {
    path: '/terms',
    title: 'Terms and Conditions',
    description: 'Read the terms and conditions for using MakeCV resume, cover letter, and career tools.',
    heading: 'Terms and Conditions',
    changefreq: 'yearly',
    priority: '0.2',
  },
  {
    path: '/privacy',
    title: 'Privacy Policy',
    description: 'Learn how MakeCV collects, uses, and protects personal information and resume data.',
    heading: 'Privacy Policy',
    changefreq: 'yearly',
    priority: '0.2',
  },
  {
    path: '/refund-policy',
    title: 'Refund Policy',
    description: 'Review MakeCV cancellation and refund policies for subscriptions and services.',
    heading: 'Refund Policy',
    changefreq: 'yearly',
    priority: '0.2',
  },
  {
    path: '/shipping-policy',
    title: 'Digital Delivery and Shipping Policy',
    description: 'Information about the digital delivery of MakeCV products and services.',
    heading: 'Digital Delivery and Shipping Policy',
    changefreq: 'yearly',
    priority: '0.2',
  },
];

export function completeTitle(title) {
  return new RegExp(`\\b${SITE_NAME}\\b`, 'i').test(title)
    ? title
    : `${title} | ${SITE_NAME}`;
}
