// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkhnxiqvghvejdulvmmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRraG54aXF2Z2h2ZWpkdWx2bW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NzUyODksImV4cCI6MjA1OTE1MTI4OX0.sbAp0cYt7vCPTEzUvI5_IND_hsbG2vtKLsbAGR4rOJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);